openapi: 3.1.1

info:
  title: API Firts Course
  version: 1.0.0
  description: API de ejemplo para el curso de API REST
servers:
  - url: http://localhost:3000
paths:
  /hello:
    get:
      summary: Hello World
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object

